apiVersion: v1
kind: Service
metadata:
  name: $GKE_SERVICE
spec:
  type: ClusterIP
  selector:
    app: $GKE_APP_NAME
  ports:
  - port: 8080
    targetPort: 80
#  - port: 80
#    targetPort: 8080
